# Generated by Django 3.1.3 on 2021-04-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='Name of the filter', max_length=100, unique=True, verbose_name='Name')),
                ('exposure_time', models.FloatField(help_text='Exposure time, in seconds.', verbose_name='Exposure Time')),
                ('exposure_count', models.IntegerField(help_text='Number of exposures.', verbose_name='Exposure Count')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The time which this target was created in the TOM database.', verbose_name='Time Created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='The time which this target was changed in the TOM database.', verbose_name='Last Modified')),
            ],
        ),
    ]
