# Generated by Django 3.2.5 on 2021-07-23 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('targeted_calibrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('enclosure', models.CharField(max_length=20)),
                ('site', models.CharField(max_length=3)),
                ('telescope', models.CharField(max_length=20)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_age', models.IntegerField(default=5)),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targeted_calibrations.filter')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targeted_calibrations.instrument')),
            ],
        ),
    ]
