# Generated by Django 3.1.1 on 2020-10-01 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibrations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enclosure',
            name='site',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='autoguider_camera',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='science_camera',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='telescope',
        ),
        migrations.RemoveField(
            model_name='telescope',
            name='enclosure',
        ),
        migrations.DeleteModel(
            name='Camera',
        ),
        migrations.DeleteModel(
            name='CameraType',
        ),
        migrations.DeleteModel(
            name='Enclosure',
        ),
        migrations.DeleteModel(
            name='FilterWheel',
        ),
        migrations.DeleteModel(
            name='Instrument',
        ),
        migrations.DeleteModel(
            name='OpticalElementGroup',
        ),
        migrations.DeleteModel(
            name='Site',
        ),
        migrations.DeleteModel(
            name='Telescope',
        ),
    ]
