# Generated by Django 3.2.5 on 2021-07-30 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calibrations', '0002_auto_20201001_2343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='Name of the filter', max_length=100, unique=True, verbose_name='Name')),
                ('exposure_time', models.FloatField(help_text='Exposure time, in seconds.', verbose_name='Exposure Time')),
                ('exposure_count', models.IntegerField(help_text='Number of exposures.', verbose_name='Exposure Count')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The time which this target was created in the TOM database.', verbose_name='Time Created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='The time which this target was changed in the TOM database.', verbose_name='Last Modified')),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('enclosure', models.CharField(max_length=20)),
                ('site', models.CharField(max_length=3)),
                ('telescope', models.CharField(max_length=20)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_age', models.IntegerField(default=5)),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calibrations.filter')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calibrations.instrument')),
            ],
        ),
    ]
