# Generated by Django 4.2.10 on 2024-12-11 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibrations', '0004_filterset_instrumentfilterset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filterset',
            old_name='filter_set_code',
            new_name='filter_combination',
        ),
    ]
