# dependencies moved to Chart.yaml for helm3
# This file required for proper helmPipeline behaviour
# Remove this file when helmPipeline.groovy::runHelmChartDependencies
# is updated to return true if Chart.yaml has dependencies.