# Production Deployment configuration values
#
# The configuration values in this file override the default values from the
# `helm-chart/values.yaml` file. This file only needs to contain the settings
# which need to be customized for the Production Environment.

# Production applications need multiple replicas for high availability
replicaCount: 1

# Configure HTTP endpoint
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx-ingress-private"
  hosts:
    - host: "calibration-tom.lco.gtn"
      paths:
        - "/"
