# Production Deployment configuration values
#
# The configuration values in this file override the default values from the
# `helm-chart/values.yaml` file. This file only needs to contain the settings
# which need to be customized for the Production Environment.

# Production applications need multiple replicas for high availability
# TODO: bump replicaCount after change from sqlite3 to postgresql
replicaCount: 1

# CronJob: cron_trigger management command
crontrigger:
  enabled: true
  resources:
    requests:
      cpu: 10m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1024Mi

djangoDebug: false

lcoServices:
  configdbURL: "http://configdb.lco.gtn"
  observationPortalURL: "http://observe.lco.global"

resources:
  requests:
    cpu: 50m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1024Mi

# Configure HTTP endpoint
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx-ingress-private"
  hosts:
    - host: "calibration-tom.lco.gtn"
      paths:
        - "/"
