# Generated by Django 4.2.1 on 2023-08-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', help_text='The code identifying the instrument e.g. kb95', max_length=10, unique=True, verbose_name='Code')),
                ('instrument', models.CharField(default='', help_text='The full site.enclosure.telescope.code designation of the instrument e.g. coj.clma.0m4a.kb24', max_length=100, unique=True, verbose_name='Instrument')),
                ('instrument_type', models.CharField(choices=[('2M0-SCICAM-SPECTRAL', '2m0-SciCam-Spectral'), ('2M0-SCICAM-MUSCAT', '2m0-SciCam-MuSCAT'), ('2M0-FLOYDS-SCICAM', '2m0-FLOYDS-SciCam'), ('1M0-SCICAM-SINISTRO', '1m0-SciCam-Sinistro'), ('1M0-NRES-SCICAM', '1m0-NRES-SciCam'), ('0M4-SCICAM-SBIG', '0m4-SciCam-SBIG')], help_text='The type of instrument, e.g. 1m0-SciCam-Sinistro.', max_length=100, verbose_name='Instrument Type')),
                ('state', models.CharField(choices=[('DISABLED', 'Disabled'), ('MANUAL', 'Manual'), ('COMMISSIONING', 'Commissioning'), ('STANDBY', 'Standby'), ('SCHEDULABLE', 'Schedulable')], help_text='The instrument state, e.g. SCHEDULABLE.', max_length=100, verbose_name='Instrument State')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The time at which the instrument was created in the Calibration-TOM.', verbose_name='Time Created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='The time at which the instrument was last updated in the Calibration-TOM.', verbose_name='Last Modified')),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the instrument list.', max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The time which this instrument list was created in the Calibration-TOM.')),
                ('modified', models.DateTimeField(auto_now=True, help_text='The time which this instrument list was changed in the Calibration-TOM.', verbose_name='Last Modified')),
                ('instruments', models.ManyToManyField(to='network.instrument')),
            ],
            options={
                'ordering': ('-created', 'name'),
            },
        ),
    ]
