{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "calibration-tom.serviceAccountName" . }}
  labels:
{{ include "calibration-tom.labels" . | indent 4 }}
{{- end -}}
