# Generated by Django 3.2.5 on 2021-07-30 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nres_calibrations', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Filter',
        ),
    ]
